require "scripts.out"
go.property("Direction", vmath.vector3())

function init(self)
	self.script = Rocket()
	self.script:AssignProperties(self)
	support.Component.Register(self.script.LocatorUrl, self.script, Rocket)
	self.script:init()
end

function final(self)
	self.script:final()
end

function update(self, dt)
	self.script:update(dt)
end

function on_message(self, message_id, message, sender)
	self.script:on_message(message_id, message, sender)
end

