require "scripts.out"
go.property("min_x", 0)
go.property("max_x", 640)

function init(self)
	self.script = Scenes.BunnymarkAnimateMultipleCollection()
	self.script:AssignProperties(self)
	support.Component.Register(self.script.LocatorUrl, self.script, Scenes.BunnymarkAnimateMultipleCollection)
	self.script:init()
end

function final(self)
	self.script:final()
end

function on_input(self, action_id, action)
	return self.script:on_input(action_id, action)
end

